name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: mcresources
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mcresources/requirements.txt
          pip install setuptools wheel twine
      - name: Read version
        id: get_version
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            return '${{ github.ref }}'.replace('refs/tags/v', '');
      - name: Test
        working-directory: ./mcresources
        run: |
          python -m pytest
      - name: Create Release
        id: create_release
        if: ${{ steps.get_version.outputs.result != '0' }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: mcresources ${{ steps.get_version.outputs.result }}
          tag_name: v${{ steps.get_version.outputs.result }}
          body_path: ./mcresources/CHANGELOG.txt
      - name: Publish
        if: ${{ steps.get_version.outputs.result != '0' }}
        working-directory: ./mcresources
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.result }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
      - name: Update Docs
        working-directory: ./mcresources
        run: |
          python docs.py
      - name: Publish Docs
        uses: spenserblack/actions-wiki@v0.3.0
        with:
          path: wiki
